// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: srv/casbin/proto/casbin.proto

package micro_arch_srv_casbin

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NewEnforcerRequest struct {
	ModelText            string   `protobuf:"bytes,1,opt,name=modelText,proto3" json:"modelText,omitempty"`
	AdapterHandle        int32    `protobuf:"varint,2,opt,name=adapterHandle,proto3" json:"adapterHandle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewEnforcerRequest) Reset()         { *m = NewEnforcerRequest{} }
func (m *NewEnforcerRequest) String() string { return proto.CompactTextString(m) }
func (*NewEnforcerRequest) ProtoMessage()    {}
func (*NewEnforcerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f441eaf2704064b, []int{0}
}
func (m *NewEnforcerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewEnforcerRequest.Unmarshal(m, b)
}
func (m *NewEnforcerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewEnforcerRequest.Marshal(b, m, deterministic)
}
func (m *NewEnforcerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewEnforcerRequest.Merge(m, src)
}
func (m *NewEnforcerRequest) XXX_Size() int {
	return xxx_messageInfo_NewEnforcerRequest.Size(m)
}
func (m *NewEnforcerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewEnforcerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewEnforcerRequest proto.InternalMessageInfo

func (m *NewEnforcerRequest) GetModelText() string {
	if m != nil {
		return m.ModelText
	}
	return ""
}

func (m *NewEnforcerRequest) GetAdapterHandle() int32 {
	if m != nil {
		return m.AdapterHandle
	}
	return 0
}

type NewEnforcerReply struct {
	Handler              int32    `protobuf:"varint,1,opt,name=handler,proto3" json:"handler,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewEnforcerReply) Reset()         { *m = NewEnforcerReply{} }
func (m *NewEnforcerReply) String() string { return proto.CompactTextString(m) }
func (*NewEnforcerReply) ProtoMessage()    {}
func (*NewEnforcerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f441eaf2704064b, []int{1}
}
func (m *NewEnforcerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewEnforcerReply.Unmarshal(m, b)
}
func (m *NewEnforcerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewEnforcerReply.Marshal(b, m, deterministic)
}
func (m *NewEnforcerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewEnforcerReply.Merge(m, src)
}
func (m *NewEnforcerReply) XXX_Size() int {
	return xxx_messageInfo_NewEnforcerReply.Size(m)
}
func (m *NewEnforcerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NewEnforcerReply.DiscardUnknown(m)
}

var xxx_messageInfo_NewEnforcerReply proto.InternalMessageInfo

func (m *NewEnforcerReply) GetHandler() int32 {
	if m != nil {
		return m.Handler
	}
	return 0
}

type NewAdapterRequest struct {
	AdapterName          string   `protobuf:"bytes,1,opt,name=adapterName,proto3" json:"adapterName,omitempty"`
	DriverName           string   `protobuf:"bytes,2,opt,name=driverName,proto3" json:"driverName,omitempty"`
	ConnectString        string   `protobuf:"bytes,3,opt,name=connectString,proto3" json:"connectString,omitempty"`
	DbSpecified          bool     `protobuf:"varint,4,opt,name=dbSpecified,proto3" json:"dbSpecified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAdapterRequest) Reset()         { *m = NewAdapterRequest{} }
func (m *NewAdapterRequest) String() string { return proto.CompactTextString(m) }
func (*NewAdapterRequest) ProtoMessage()    {}
func (*NewAdapterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f441eaf2704064b, []int{2}
}
func (m *NewAdapterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAdapterRequest.Unmarshal(m, b)
}
func (m *NewAdapterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAdapterRequest.Marshal(b, m, deterministic)
}
func (m *NewAdapterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAdapterRequest.Merge(m, src)
}
func (m *NewAdapterRequest) XXX_Size() int {
	return xxx_messageInfo_NewAdapterRequest.Size(m)
}
func (m *NewAdapterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAdapterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewAdapterRequest proto.InternalMessageInfo

func (m *NewAdapterRequest) GetAdapterName() string {
	if m != nil {
		return m.AdapterName
	}
	return ""
}

func (m *NewAdapterRequest) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *NewAdapterRequest) GetConnectString() string {
	if m != nil {
		return m.ConnectString
	}
	return ""
}

func (m *NewAdapterRequest) GetDbSpecified() bool {
	if m != nil {
		return m.DbSpecified
	}
	return false
}

type NewAdapterReply struct {
	Handler              int32    `protobuf:"varint,1,opt,name=handler,proto3" json:"handler,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAdapterReply) Reset()         { *m = NewAdapterReply{} }
func (m *NewAdapterReply) String() string { return proto.CompactTextString(m) }
func (*NewAdapterReply) ProtoMessage()    {}
func (*NewAdapterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f441eaf2704064b, []int{3}
}
func (m *NewAdapterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAdapterReply.Unmarshal(m, b)
}
func (m *NewAdapterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAdapterReply.Marshal(b, m, deterministic)
}
func (m *NewAdapterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAdapterReply.Merge(m, src)
}
func (m *NewAdapterReply) XXX_Size() int {
	return xxx_messageInfo_NewAdapterReply.Size(m)
}
func (m *NewAdapterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAdapterReply.DiscardUnknown(m)
}

var xxx_messageInfo_NewAdapterReply proto.InternalMessageInfo

func (m *NewAdapterReply) GetHandler() int32 {
	if m != nil {
		return m.Handler
	}
	return 0
}

type PolicyRequest struct {
	EnforcerHandler      int32    `protobuf:"varint,1,opt,name=enforcerHandler,proto3" json:"enforcerHandler,omitempty"`
	PType                string   `protobuf:"bytes,2,opt,name=pType,proto3" json:"pType,omitempty"`
	Params               []string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolicyRequest) Reset()         { *m = PolicyRequest{} }
func (m *PolicyRequest) String() string { return proto.CompactTextString(m) }
func (*PolicyRequest) ProtoMessage()    {}
func (*PolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f441eaf2704064b, []int{4}
}
func (m *PolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyRequest.Unmarshal(m, b)
}
func (m *PolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyRequest.Marshal(b, m, deterministic)
}
func (m *PolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyRequest.Merge(m, src)
}
func (m *PolicyRequest) XXX_Size() int {
	return xxx_messageInfo_PolicyRequest.Size(m)
}
func (m *PolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyRequest proto.InternalMessageInfo

func (m *PolicyRequest) GetEnforcerHandler() int32 {
	if m != nil {
		return m.EnforcerHandler
	}
	return 0
}

func (m *PolicyRequest) GetPType() string {
	if m != nil {
		return m.PType
	}
	return ""
}

func (m *PolicyRequest) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

type EnforceRequest struct {
	EnforcerHandler      int32    `protobuf:"varint,1,opt,name=enforcerHandler,proto3" json:"enforcerHandler,omitempty"`
	Params               []string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnforceRequest) Reset()         { *m = EnforceRequest{} }
func (m *EnforceRequest) String() string { return proto.CompactTextString(m) }
func (*EnforceRequest) ProtoMessage()    {}
func (*EnforceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f441eaf2704064b, []int{5}
}
func (m *EnforceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnforceRequest.Unmarshal(m, b)
}
func (m *EnforceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnforceRequest.Marshal(b, m, deterministic)
}
func (m *EnforceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnforceRequest.Merge(m, src)
}
func (m *EnforceRequest) XXX_Size() int {
	return xxx_messageInfo_EnforceRequest.Size(m)
}
func (m *EnforceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnforceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnforceRequest proto.InternalMessageInfo

func (m *EnforceRequest) GetEnforcerHandler() int32 {
	if m != nil {
		return m.EnforcerHandler
	}
	return 0
}

func (m *EnforceRequest) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

type UserRoleRequest struct {
	EnforcerHandler      int32    `protobuf:"varint,1,opt,name=enforcerHandler,proto3" json:"enforcerHandler,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRoleRequest) Reset()         { *m = UserRoleRequest{} }
func (m *UserRoleRequest) String() string { return proto.CompactTextString(m) }
func (*UserRoleRequest) ProtoMessage()    {}
func (*UserRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f441eaf2704064b, []int{6}
}
func (m *UserRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRoleRequest.Unmarshal(m, b)
}
func (m *UserRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRoleRequest.Marshal(b, m, deterministic)
}
func (m *UserRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRoleRequest.Merge(m, src)
}
func (m *UserRoleRequest) XXX_Size() int {
	return xxx_messageInfo_UserRoleRequest.Size(m)
}
func (m *UserRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRoleRequest proto.InternalMessageInfo

func (m *UserRoleRequest) GetEnforcerHandler() int32 {
	if m != nil {
		return m.EnforcerHandler
	}
	return 0
}

func (m *UserRoleRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *UserRoleRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type EmptyRequest struct {
	Handler              int32    `protobuf:"varint,1,opt,name=handler,proto3" json:"handler,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f441eaf2704064b, []int{7}
}
func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

func (m *EmptyRequest) GetHandler() int32 {
	if m != nil {
		return m.Handler
	}
	return 0
}

type EmptyReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReply) Reset()         { *m = EmptyReply{} }
func (m *EmptyReply) String() string { return proto.CompactTextString(m) }
func (*EmptyReply) ProtoMessage()    {}
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f441eaf2704064b, []int{8}
}
func (m *EmptyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReply.Unmarshal(m, b)
}
func (m *EmptyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReply.Marshal(b, m, deterministic)
}
func (m *EmptyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReply.Merge(m, src)
}
func (m *EmptyReply) XXX_Size() int {
	return xxx_messageInfo_EmptyReply.Size(m)
}
func (m *EmptyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReply proto.InternalMessageInfo

func (m *EmptyReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ArrayReply struct {
	Array                []string `protobuf:"bytes,1,rep,name=array,proto3" json:"array,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArrayReply) Reset()         { *m = ArrayReply{} }
func (m *ArrayReply) String() string { return proto.CompactTextString(m) }
func (*ArrayReply) ProtoMessage()    {}
func (*ArrayReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f441eaf2704064b, []int{9}
}
func (m *ArrayReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayReply.Unmarshal(m, b)
}
func (m *ArrayReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayReply.Marshal(b, m, deterministic)
}
func (m *ArrayReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayReply.Merge(m, src)
}
func (m *ArrayReply) XXX_Size() int {
	return xxx_messageInfo_ArrayReply.Size(m)
}
func (m *ArrayReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayReply.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayReply proto.InternalMessageInfo

func (m *ArrayReply) GetArray() []string {
	if m != nil {
		return m.Array
	}
	return nil
}

func init() {
	proto.RegisterType((*NewEnforcerRequest)(nil), "micro.arch.srv.casbin.NewEnforcerRequest")
	proto.RegisterType((*NewEnforcerReply)(nil), "micro.arch.srv.casbin.NewEnforcerReply")
	proto.RegisterType((*NewAdapterRequest)(nil), "micro.arch.srv.casbin.NewAdapterRequest")
	proto.RegisterType((*NewAdapterReply)(nil), "micro.arch.srv.casbin.NewAdapterReply")
	proto.RegisterType((*PolicyRequest)(nil), "micro.arch.srv.casbin.PolicyRequest")
	proto.RegisterType((*EnforceRequest)(nil), "micro.arch.srv.casbin.EnforceRequest")
	proto.RegisterType((*UserRoleRequest)(nil), "micro.arch.srv.casbin.UserRoleRequest")
	proto.RegisterType((*EmptyRequest)(nil), "micro.arch.srv.casbin.EmptyRequest")
	proto.RegisterType((*EmptyReply)(nil), "micro.arch.srv.casbin.EmptyReply")
	proto.RegisterType((*ArrayReply)(nil), "micro.arch.srv.casbin.ArrayReply")
}

func init() { proto.RegisterFile("srv/casbin/proto/casbin.proto", fileDescriptor_6f441eaf2704064b) }

var fileDescriptor_6f441eaf2704064b = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0x7f, 0x4f, 0xd4, 0x4c,
	0x10, 0xc7, 0x29, 0x70, 0xc0, 0x0d, 0x3f, 0xee, 0x61, 0xc3, 0x83, 0x0d, 0x51, 0x73, 0x56, 0xc4,
	0x1a, 0x4d, 0x49, 0xf4, 0x15, 0x5c, 0x14, 0xc1, 0xc4, 0x10, 0x53, 0xc0, 0x68, 0x0c, 0x84, 0x65,
	0x77, 0x38, 0x9a, 0xb4, 0xdd, 0xba, 0xdb, 0x3b, 0xbc, 0x17, 0xe3, 0xdb, 0xf2, 0xf5, 0x98, 0x6e,
	0xb7, 0xf4, 0x8a, 0x96, 0x1c, 0xe6, 0xfa, 0x5f, 0x67, 0x76, 0xe6, 0xf3, 0x9d, 0x99, 0x9b, 0xdd,
	0x1c, 0x3c, 0x52, 0x72, 0xb8, 0xcb, 0xa8, 0xba, 0x08, 0xe2, 0xdd, 0x44, 0x8a, 0x54, 0x18, 0xc3,
	0xd3, 0x06, 0xf9, 0x3f, 0x0a, 0x98, 0x14, 0x1e, 0x95, 0xec, 0xca, 0x53, 0x72, 0xe8, 0xe5, 0x87,
	0xce, 0x17, 0x20, 0x87, 0x78, 0xbd, 0x17, 0x5f, 0x0a, 0xc9, 0x50, 0xfa, 0xf8, 0x7d, 0x80, 0x2a,
	0x25, 0x0f, 0xa1, 0x1d, 0x09, 0x8e, 0xe1, 0x31, 0xfe, 0x48, 0x6d, 0xab, 0x6b, 0xb9, 0x6d, 0xbf,
	0x74, 0x90, 0x6d, 0x58, 0xa5, 0x9c, 0x26, 0x29, 0xca, 0x03, 0x1a, 0xf3, 0x10, 0xed, 0xd9, 0xae,
	0xe5, 0xb6, 0xfc, 0xaa, 0xd3, 0x79, 0x05, 0xff, 0x55, 0xc8, 0x49, 0x38, 0x22, 0x36, 0x2c, 0x5e,
	0xe9, 0x53, 0xa9, 0xa9, 0x2d, 0xbf, 0x30, 0x9d, 0x9f, 0x16, 0xac, 0x1f, 0xe2, 0x75, 0x2f, 0x47,
	0x14, 0x75, 0x74, 0x61, 0xd9, 0x40, 0x0f, 0x69, 0x84, 0xa6, 0x92, 0x71, 0x17, 0x79, 0x0c, 0xc0,
	0x65, 0x30, 0x34, 0x01, 0xb3, 0x3a, 0x60, 0xcc, 0x93, 0xd5, 0xca, 0x44, 0x1c, 0x23, 0x4b, 0x8f,
	0x52, 0x19, 0xc4, 0x7d, 0x7b, 0x4e, 0x87, 0x54, 0x9d, 0x99, 0x0e, 0xbf, 0x38, 0x4a, 0x90, 0x05,
	0x97, 0x01, 0x72, 0x7b, 0xbe, 0x6b, 0xb9, 0x4b, 0xfe, 0xb8, 0xcb, 0x79, 0x09, 0x9d, 0xf1, 0xf2,
	0xee, 0x6e, 0xa6, 0x0f, 0xab, 0x9f, 0x44, 0x18, 0xb0, 0x51, 0xd1, 0x87, 0x0b, 0x1d, 0x34, 0x83,
	0x38, 0xa8, 0xa4, 0xdc, 0x76, 0x93, 0x0d, 0x68, 0x25, 0xc7, 0xa3, 0xa4, 0x68, 0x25, 0x37, 0xc8,
	0x26, 0x2c, 0x24, 0x54, 0xd2, 0x48, 0xd9, 0x73, 0xdd, 0x39, 0xb7, 0xed, 0x1b, 0xcb, 0xf1, 0x61,
	0xcd, 0x0c, 0xf8, 0xfe, 0x4a, 0x25, 0x73, 0xb6, 0xc2, 0x64, 0xd0, 0x39, 0x51, 0x28, 0x7d, 0x11,
	0xfe, 0x03, 0x94, 0xc0, 0xfc, 0x40, 0xa1, 0x34, 0xd5, 0xeb, 0xef, 0xcc, 0x27, 0x45, 0x88, 0x66,
	0xf2, 0xfa, 0xdb, 0x71, 0x61, 0x65, 0x2f, 0x4a, 0xd2, 0x9b, 0x01, 0xd5, 0xcf, 0x72, 0x07, 0xc0,
	0x44, 0x9a, 0x99, 0xab, 0x01, 0x63, 0xa8, 0x94, 0x8e, 0x5b, 0xf2, 0x0b, 0xd3, 0x71, 0x00, 0x7a,
	0x52, 0x52, 0x13, 0xb7, 0x01, 0x2d, 0x9a, 0x59, 0xb6, 0xa5, 0x7b, 0xcb, 0x8d, 0xd7, 0xbf, 0x56,
	0x60, 0xe1, 0xad, 0xde, 0x7b, 0xc2, 0x60, 0x79, 0x6c, 0x3b, 0xc9, 0x0b, 0xef, 0xaf, 0xd7, 0xc3,
	0xfb, 0xf3, 0x6e, 0x6c, 0x3d, 0x9f, 0x24, 0x34, 0x09, 0x47, 0xce, 0x0c, 0x39, 0x07, 0x28, 0x97,
	0x86, 0xb8, 0xf5, 0x89, 0xd5, 0xb5, 0xdf, 0xda, 0x99, 0x20, 0x32, 0x57, 0x38, 0x81, 0x45, 0x23,
	0x4a, 0x9e, 0xd5, 0x24, 0x55, 0x17, 0x64, 0xeb, 0x49, 0x5d, 0xd8, 0xcd, 0x90, 0x9d, 0x19, 0xf2,
	0x19, 0xe0, 0xa3, 0xa0, 0x3c, 0x5f, 0x62, 0xf2, 0xf4, 0xee, 0x94, 0xfb, 0x71, 0x8f, 0xe8, 0x10,
	0x1b, 0xe0, 0xb6, 0x7b, 0xbc, 0x28, 0x77, 0xbb, 0x26, 0xa3, 0x72, 0x25, 0x27, 0xe3, 0x7e, 0x83,
	0xb5, 0x1e, 0xe7, 0xd9, 0x43, 0xd2, 0x00, 0xfc, 0x0c, 0xd6, 0x7b, 0x9c, 0xef, 0x4b, 0x31, 0x48,
	0x82, 0xb8, 0x3f, 0x7d, 0x3e, 0x83, 0xcd, 0xa2, 0xf8, 0xe6, 0x44, 0xce, 0xa0, 0xb3, 0x8f, 0x69,
	0xf6, 0x58, 0xa8, 0xf7, 0x42, 0x66, 0x0f, 0x07, 0xa9, 0xdb, 0xde, 0x5b, 0xaf, 0x4a, 0x2d, 0xbf,
	0xbc, 0xc6, 0xce, 0x0c, 0xb9, 0x84, 0x07, 0xfb, 0x98, 0x7e, 0x88, 0x92, 0x30, 0x60, 0x41, 0x83,
	0x3a, 0x79, 0x1f, 0x59, 0x6a, 0xc6, 0xcf, 0xd2, 0xa7, 0xcb, 0x3f, 0x85, 0xb5, 0x03, 0xaa, 0xb2,
	0xb4, 0x69, 0x95, 0x5f, 0xf9, 0x19, 0x4e, 0xf5, 0xa2, 0x36, 0x86, 0x3f, 0x87, 0xf5, 0x77, 0x18,
	0x62, 0x8a, 0x8d, 0x29, 0x50, 0x20, 0xa5, 0x82, 0x6a, 0x44, 0xe2, 0x2b, 0x40, 0x29, 0x31, 0x55,
	0xf4, 0xc5, 0x82, 0xfe, 0x8f, 0xf5, 0xe6, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x43, 0xe5, 0xa4,
	0x64, 0x84, 0x09, 0x00, 0x00,
}
