// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: srv/user/proto/user.proto

package micro_arch_srv_user

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_30a4fe46b2307fe5, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_30a4fe46b2307fe5, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_30a4fe46b2307fe5, []int{2}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type User struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" valid:stringlength(1|32),required`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty" valid:url`
	CreatedAt            int64    `protobuf:"varint,4,opt,name=createdAt,proto3" json:"created_at"`
	UpdatedAt            int64    `protobuf:"varint,5,opt,name=updatedAt,proto3" json:"updated_at"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_30a4fe46b2307fe5, []int{3}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "micro.arch.srv.user.Request")
	proto.RegisterType((*Response)(nil), "micro.arch.srv.user.Response")
	proto.RegisterType((*Error)(nil), "micro.arch.srv.user.Error")
	proto.RegisterType((*User)(nil), "micro.arch.srv.user.user")
}

func init() { proto.RegisterFile("srv/user/proto/user.proto", fileDescriptor_30a4fe46b2307fe5) }

var fileDescriptor_30a4fe46b2307fe5 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xbf, 0x8e, 0xd3, 0x40,
	0x10, 0xc6, 0x71, 0xce, 0xce, 0x9d, 0x07, 0xdd, 0x15, 0x8b, 0x84, 0x7c, 0x11, 0x28, 0x87, 0xa5,
	0x93, 0x82, 0x74, 0xe7, 0x40, 0xd2, 0x00, 0x1d, 0x41, 0x34, 0x50, 0xb1, 0x12, 0x35, 0xda, 0x78,
	0x07, 0x67, 0x25, 0xc7, 0x9b, 0xdb, 0x3f, 0x96, 0x90, 0x68, 0x79, 0x0e, 0x5e, 0x8a, 0x3a, 0x0f,
	0x40, 0x99, 0x27, 0x40, 0x9e, 0x35, 0x49, 0x13, 0x24, 0x8a, 0x6b, 0xac, 0x99, 0x9d, 0xdf, 0xf7,
	0xed, 0x67, 0x8f, 0xe1, 0xd2, 0x9a, 0x76, 0xea, 0x2d, 0x9a, 0xe9, 0xc6, 0x68, 0xa7, 0xa9, 0x2c,
	0xa8, 0x64, 0x8f, 0xd6, 0xaa, 0x34, 0xba, 0x10, 0xa6, 0x5c, 0x15, 0xd6, 0xb4, 0x45, 0x37, 0x1a,
	0xdd, 0x56, 0xca, 0xad, 0xfc, 0xb2, 0x28, 0xf5, 0x7a, 0x5a, 0xe9, 0x4a, 0x07, 0xd9, 0xd2, 0x7f,
	0xa5, 0x2e, 0x78, 0x74, 0x55, 0xf0, 0xc8, 0x5f, 0xc1, 0x29, 0xc7, 0x3b, 0x8f, 0xd6, 0xb1, 0x5b,
	0x88, 0x3b, 0x87, 0x2c, 0xba, 0x8a, 0x26, 0x0f, 0x67, 0x97, 0xc5, 0x11, 0x77, 0x7a, 0x70, 0xc2,
	0xf2, 0x1f, 0x11, 0x9c, 0x71, 0xb4, 0x1b, 0xdd, 0x58, 0x64, 0x19, 0x9c, 0x5a, 0x5f, 0x96, 0x68,
	0x2d, 0xc9, 0xcf, 0xf8, 0xdf, 0x96, 0xbd, 0x80, 0x04, 0x8d, 0xd1, 0x26, 0x1b, 0x90, 0xed, 0xe8,
	0xa8, 0xed, 0xfb, 0x8e, 0xe0, 0x01, 0xdc, 0xe7, 0x38, 0xf9, 0xbf, 0x1c, 0x73, 0x48, 0x48, 0xce,
	0x18, 0xc4, 0xa5, 0x96, 0x48, 0x01, 0x12, 0x4e, 0x35, 0x7b, 0x0c, 0x43, 0x89, 0x4e, 0xa8, 0x9a,
	0xae, 0x4f, 0x79, 0xdf, 0xe5, 0xbf, 0xa2, 0x70, 0x09, 0xbb, 0x80, 0x81, 0x92, 0x24, 0x39, 0xe7,
	0x03, 0x25, 0xd9, 0x6b, 0x88, 0x1b, 0xb1, 0xc6, 0x80, 0x2f, 0xae, 0x77, 0xdb, 0xf1, 0xb3, 0x56,
	0xd4, 0x4a, 0xbe, 0xb1, 0xce, 0xa8, 0xa6, 0xaa, 0xb1, 0xa9, 0xdc, 0x6a, 0xf2, 0xf2, 0xfb, 0x7c,
	0xf6, 0xfc, 0xc6, 0xe0, 0x9d, 0x57, 0x06, 0x25, 0x27, 0x09, 0xbb, 0x86, 0xa1, 0x68, 0x85, 0x13,
	0x21, 0x79, 0xba, 0x38, 0xdf, 0x6d, 0xc7, 0x69, 0x10, 0x7b, 0x53, 0xf3, 0x7e, 0xc8, 0x6e, 0x20,
	0x2d, 0x0d, 0x0a, 0x87, 0xf2, 0xad, 0xcb, 0xe2, 0xab, 0x68, 0x72, 0xb2, 0xb8, 0xf8, 0xbd, 0x1d,
	0x43, 0x7f, 0xf8, 0x45, 0x38, 0x7e, 0x00, 0x3a, 0xda, 0x6f, 0x64, 0x4f, 0x27, 0x07, 0xba, 0x3f,
	0x24, 0x7a, 0x0f, 0xcc, 0x7e, 0x46, 0x10, 0x7f, 0xee, 0x5e, 0xeb, 0x23, 0xc0, 0x3b, 0xf2, 0xa0,
	0xee, 0xc9, 0xd1, 0x6f, 0xd8, 0xef, 0x7d, 0xf4, 0xf4, 0x1f, 0xd3, 0xb0, 0xda, 0xfc, 0x01, 0xfb,
	0x00, 0xe9, 0x27, 0x8f, 0xe6, 0xdb, 0x3d, 0x78, 0x2d, 0x87, 0xf4, 0xdb, 0xcd, 0xff, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x99, 0xe6, 0x48, 0x8d, 0xd7, 0x02, 0x00, 0x00,
}
