
version: '3'

services:
  etcd:
    container_name: arch_etcd
    image: quay.io/coreos/etcd:v3.3.18
    command:
      /usr/local/bin/etcd
      --name s1
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://0.0.0.0:2380
      --initial-cluster s1=http://0.0.0.0:2380
      --initial-cluster-token tkn
      --initial-cluster-state new
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - "/tmp/etcd-data.tmp:/etcd-data"

  config:
    build:
      context: ../
      dockerfile: ./infra/config/Dockerfile
    container_name: arch_config
    volumes:
      - "../infra/config/config.yml:/app/config.yml"
    ports:
      - "9689:9689"
    restart: always
    networks:
      - net

networks:
  net:
    driver: bridge
