
version: '3'

services:
  etcd:
    container_name: arch_etcd
    image: quay.io/coreos/etcd:v3.3.18
    command:
      /usr/local/bin/etcd
      --name s1
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://0.0.0.0:2380
      --initial-cluster s1=http://0.0.0.0:2380
      --initial-cluster-token tkn
      --initial-cluster-state new
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - "/tmp/etcd-data.tmp:/etcd-data"

  config:
    build:
      context: ../
      dockerfile: ./infra/config/Dockerfile
    container_name: arch_config
    volumes:
      - "../infra/config/config.yml:/app/config.yml"
    ports:
      - "9689:9689"
    restart: always
    networks:
      - net

  gateway:
    depends_on:
      - config
      - etcd
    networks:
      - net
    build:
      context: ../
      dockerfile: ./infra/gateway/Dockerfile
    command: /app/main api
    environment:
      MICRO_REGISTRY: etcd
      MICRO_REGISTRY_ADDRESS: host.docker.internal:2379
      MICRO_API_NAMESPACE: micro.arch.web
      MICRO_API_HANDLER: rpc
      # enable /rpc endpoint when using rpc handler, just for debug
      MICRO_API_ENABLE_RPC: 'true'
      ARCH_CONFIG_ADDR: "config:9689"
    ports:
      - "8080:8080"

networks:
  net:
    driver: bridge
