// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/auth/proto/auth.proto

package micro_arch_srv_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	UserId               uint32   `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a9cb9a112a8986, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Request struct {
	AuthType             uint32   `protobuf:"varint,1,opt,name=AuthType,proto3" json:"AuthType,omitempty"`
	AuthId               string   `protobuf:"bytes,2,opt,name=AuthId,proto3" json:"AuthId,omitempty"`
	Credential           string   `protobuf:"bytes,3,opt,name=Credential,proto3" json:"Credential,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a9cb9a112a8986, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetAuthType() uint32 {
	if m != nil {
		return m.AuthType
	}
	return 0
}

func (m *Request) GetAuthId() string {
	if m != nil {
		return m.AuthId
	}
	return ""
}

func (m *Request) GetCredential() string {
	if m != nil {
		return m.Credential
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a9cb9a112a8986, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*Response)(nil), "micro.arch.srv.auth.Response")
	proto.RegisterType((*Request)(nil), "micro.arch.srv.auth.Request")
	proto.RegisterType((*Error)(nil), "micro.arch.srv.auth.Error")
}

func init() { proto.RegisterFile("srv/auth/proto/auth.proto", fileDescriptor_71a9cb9a112a8986) }

var fileDescriptor_71a9cb9a112a8986 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcf, 0x4e, 0x83, 0x40,
	0x10, 0x87, 0x45, 0xfb, 0x87, 0x8e, 0xf6, 0x32, 0x26, 0x06, 0x89, 0x1a, 0xc2, 0x89, 0xd3, 0xd6,
	0xb4, 0x4f, 0x60, 0x8c, 0x07, 0x0e, 0x5e, 0x36, 0xf6, 0xe8, 0x01, 0x61, 0x0c, 0x24, 0x95, 0xc5,
	0x99, 0xa5, 0x49, 0xdf, 0xde, 0xec, 0x42, 0x8d, 0x87, 0x7a, 0xfb, 0x7d, 0xcc, 0xf0, 0xcd, 0xec,
	0xc0, 0xad, 0xf0, 0x7e, 0x55, 0xf4, 0xb6, 0x5e, 0x75, 0x6c, 0xac, 0xf1, 0x51, 0xf9, 0x88, 0xd7,
	0x5f, 0x4d, 0xc9, 0x46, 0x15, 0x5c, 0xd6, 0x4a, 0x78, 0xaf, 0x5c, 0x29, 0x6d, 0x21, 0xd4, 0x24,
	0x9d, 0x69, 0x85, 0x30, 0x82, 0xb9, 0xf4, 0x65, 0x49, 0x22, 0x51, 0x90, 0x04, 0x59, 0xa8, 0x8f,
	0x88, 0x8f, 0x30, 0x25, 0x66, 0xc3, 0xd1, 0x79, 0x12, 0x64, 0x97, 0xeb, 0x58, 0x9d, 0x50, 0xa9,
	0x17, 0xd7, 0xa1, 0x87, 0x46, 0xbc, 0x81, 0x59, 0x2f, 0xc4, 0x79, 0x15, 0x5d, 0x24, 0x41, 0xb6,
	0xd4, 0x23, 0xa5, 0xef, 0x30, 0xd7, 0xf4, 0xdd, 0x93, 0x58, 0x8c, 0x21, 0x7c, 0xea, 0x6d, 0xfd,
	0x76, 0xe8, 0xc8, 0xcf, 0x5b, 0xea, 0x5f, 0x76, 0xbf, 0xbb, 0x9c, 0x57, 0x7e, 0xe2, 0x42, 0x8f,
	0x84, 0x0f, 0x00, 0xcf, 0x4c, 0x15, 0xb5, 0xb6, 0x29, 0x76, 0x5e, 0xbd, 0xd0, 0x7f, 0xbe, 0xa4,
	0x1b, 0x98, 0xfa, 0x35, 0x10, 0x61, 0x52, 0x9a, 0x6a, 0x10, 0x4f, 0xb5, 0xcf, 0x4e, 0x5a, 0x91,
	0x2d, 0x9a, 0xdd, 0x51, 0x3a, 0xd0, 0x7a, 0x0b, 0x13, 0xa7, 0xc7, 0x57, 0xb8, 0xca, 0xbd, 0xe8,
	0xf3, 0xb0, 0x15, 0x62, 0xbc, 0x3b, 0xf9, 0xcc, 0x71, 0xfd, 0xf8, 0xfe, 0x9f, 0xea, 0x70, 0xcc,
	0xf4, 0xec, 0x63, 0xe6, 0xcf, 0xbe, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x57, 0x1f, 0xd9,
	0x93, 0x01, 0x00, 0x00,
}
