// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: srv/auth/proto/auth.proto

package micro_arch_srv_auth

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Auth service

type AuthService interface {
	CheckCredential(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	AddLoginCredential(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	VerifyToken(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	SignOff(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	SignOn(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	//    rpc GenerateOneTimeToken(Request) returns (Response) {}
	VerifySmsCode(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	CheckAuthIdInUsed(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "micro.arch.srv.auth"
	}
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) CheckCredential(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Auth.CheckCredential", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) AddLoginCredential(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Auth.AddLoginCredential", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) VerifyToken(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Auth.VerifyToken", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) SignOff(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Auth.SignOff", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) SignOn(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Auth.SignOn", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) VerifySmsCode(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Auth.VerifySmsCode", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) CheckAuthIdInUsed(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Auth.CheckAuthIdInUsed", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthHandler interface {
	CheckCredential(context.Context, *Request, *Response) error
	AddLoginCredential(context.Context, *Request, *Response) error
	VerifyToken(context.Context, *Request, *Response) error
	SignOff(context.Context, *Request, *Response) error
	SignOn(context.Context, *Request, *Response) error
	//    rpc GenerateOneTimeToken(Request) returns (Response) {}
	VerifySmsCode(context.Context, *Request, *Response) error
	CheckAuthIdInUsed(context.Context, *Request, *Response) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) error {
	type auth interface {
		CheckCredential(ctx context.Context, in *Request, out *Response) error
		AddLoginCredential(ctx context.Context, in *Request, out *Response) error
		VerifyToken(ctx context.Context, in *Request, out *Response) error
		SignOff(ctx context.Context, in *Request, out *Response) error
		SignOn(ctx context.Context, in *Request, out *Response) error
		VerifySmsCode(ctx context.Context, in *Request, out *Response) error
		CheckAuthIdInUsed(ctx context.Context, in *Request, out *Response) error
	}
	type Auth struct {
		auth
	}
	h := &authHandler{hdlr}
	return s.Handle(s.NewHandler(&Auth{h}, opts...))
}

type authHandler struct {
	AuthHandler
}

func (h *authHandler) CheckCredential(ctx context.Context, in *Request, out *Response) error {
	return h.AuthHandler.CheckCredential(ctx, in, out)
}

func (h *authHandler) AddLoginCredential(ctx context.Context, in *Request, out *Response) error {
	return h.AuthHandler.AddLoginCredential(ctx, in, out)
}

func (h *authHandler) VerifyToken(ctx context.Context, in *Request, out *Response) error {
	return h.AuthHandler.VerifyToken(ctx, in, out)
}

func (h *authHandler) SignOff(ctx context.Context, in *Request, out *Response) error {
	return h.AuthHandler.SignOff(ctx, in, out)
}

func (h *authHandler) SignOn(ctx context.Context, in *Request, out *Response) error {
	return h.AuthHandler.SignOn(ctx, in, out)
}

func (h *authHandler) VerifySmsCode(ctx context.Context, in *Request, out *Response) error {
	return h.AuthHandler.VerifySmsCode(ctx, in, out)
}

func (h *authHandler) CheckAuthIdInUsed(ctx context.Context, in *Request, out *Response) error {
	return h.AuthHandler.CheckAuthIdInUsed(ctx, in, out)
}
