// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: srv/auth/proto/auth.proto

package micro_arch_srv_auth

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AuthType int32

const (
	AuthType_Email  AuthType = 0
	AuthType_Mobile AuthType = 1
	AuthType_Github AuthType = 2
)

var AuthType_name = map[int32]string{
	0: "Email",
	1: "Mobile",
	2: "Github",
}

var AuthType_value = map[string]int32{
	"Email":  0,
	"Mobile": 1,
	"Github": 2,
}

func (x AuthType) String() string {
	return proto.EnumName(AuthType_name, int32(x))
}

func (AuthType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_71a9cb9a112a8986, []int{0}
}

type Response struct {
	Success              bool      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error    `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Token                string    `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool      `protobuf:"varint,7,opt,name=valid,proto3" json:"valid,omitempty"`
	Info                 *AuthInfo `protobuf:"bytes,8,opt,name=info,proto3" json:"auth_info"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a9cb9a112a8986, []int{0}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Response) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Response) GetInfo() *AuthInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type Request struct {
	Info                 *AuthInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"auth_info"`
	Login                bool      `protobuf:"varint,3,opt,name=login,proto3" json:"login,omitempty"`
	Token                string    `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a9cb9a112a8986, []int{1}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetInfo() *AuthInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Request) GetLogin() bool {
	if m != nil {
		return m.Login
	}
	return false
}

func (m *Request) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a9cb9a112a8986, []int{2}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type AuthInfo struct {
	Id       uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid      uint32 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Verified bool   `protobuf:"varint,5,opt,name=verified,proto3" json:"verified,omitempty"`
	// use email as default auth type
	AuthType             AuthType `protobuf:"varint,7,opt,name=authType,proto3,enum=micro.arch.srv.auth.AuthType" json:"auth_type" db:"auth_type"`
	AuthId               string   `protobuf:"bytes,9,opt,name=authId,proto3" json:"auth_id" db:"auth_id"`
	Credential           string   `protobuf:"bytes,11,opt,name=credential,proto3" json:"credential,omitempty"`
	LatestLoginAt        int64    `protobuf:"varint,13,opt,name=latestLoginAt,proto3" json:"latest_login_at"`
	IpAddr               string   `protobuf:"bytes,15,opt,name=ipAddr,proto3" json:"ip_addr"`
	CreatedAt            int64    `protobuf:"varint,17,opt,name=createdAt,proto3" json:"created_at"`
	UpdatedAt            int64    `protobuf:"varint,19,opt,name=updatedAt,proto3" json:"updated_at"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthInfo) Reset()         { *m = AuthInfo{} }
func (m *AuthInfo) String() string { return proto.CompactTextString(m) }
func (*AuthInfo) ProtoMessage()    {}
func (*AuthInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a9cb9a112a8986, []int{3}
}
func (m *AuthInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthInfo.Unmarshal(m, b)
}
func (m *AuthInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthInfo.Marshal(b, m, deterministic)
}
func (m *AuthInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthInfo.Merge(m, src)
}
func (m *AuthInfo) XXX_Size() int {
	return xxx_messageInfo_AuthInfo.Size(m)
}
func (m *AuthInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AuthInfo proto.InternalMessageInfo

func (m *AuthInfo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AuthInfo) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *AuthInfo) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *AuthInfo) GetAuthType() AuthType {
	if m != nil {
		return m.AuthType
	}
	return AuthType_Email
}

func (m *AuthInfo) GetAuthId() string {
	if m != nil {
		return m.AuthId
	}
	return ""
}

func (m *AuthInfo) GetCredential() string {
	if m != nil {
		return m.Credential
	}
	return ""
}

func (m *AuthInfo) GetLatestLoginAt() int64 {
	if m != nil {
		return m.LatestLoginAt
	}
	return 0
}

func (m *AuthInfo) GetIpAddr() string {
	if m != nil {
		return m.IpAddr
	}
	return ""
}

func (m *AuthInfo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *AuthInfo) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterEnum("micro.arch.srv.auth.AuthType", AuthType_name, AuthType_value)
	proto.RegisterType((*Response)(nil), "micro.arch.srv.auth.Response")
	proto.RegisterType((*Request)(nil), "micro.arch.srv.auth.Request")
	proto.RegisterType((*Error)(nil), "micro.arch.srv.auth.Error")
	proto.RegisterType((*AuthInfo)(nil), "micro.arch.srv.auth.AuthInfo")
}

func init() { proto.RegisterFile("srv/auth/proto/auth.proto", fileDescriptor_71a9cb9a112a8986) }

var fileDescriptor_71a9cb9a112a8986 = []byte{
	// 610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0xeb, 0xa6, 0x49, 0x9c, 0xc9, 0x2f, 0x69, 0x7e, 0x5b, 0x84, 0x4c, 0xa0, 0x38, 0x32,
	0x97, 0x08, 0x51, 0x17, 0xb5, 0x27, 0x38, 0x91, 0x54, 0x55, 0xa9, 0x54, 0x04, 0xda, 0x56, 0x1c,
	0xb8, 0x44, 0x8e, 0x77, 0x93, 0xac, 0xea, 0x7a, 0xcd, 0x7a, 0x1d, 0xd4, 0x97, 0xe0, 0x6d, 0x78,
	0x03, 0x9e, 0xc3, 0x0f, 0x90, 0x63, 0x9f, 0x00, 0xed, 0xd8, 0x75, 0x41, 0x0a, 0x1c, 0x28, 0xb7,
	0xf9, 0xf3, 0x9d, 0xcf, 0xce, 0x8c, 0x77, 0x0d, 0x8f, 0x52, 0xb5, 0xdc, 0x0f, 0x32, 0xbd, 0xd8,
	0x4f, 0x94, 0xd4, 0x12, 0x4d, 0x1f, 0x4d, 0xb2, 0x73, 0x25, 0x42, 0x25, 0xfd, 0x40, 0x85, 0x0b,
	0x3f, 0x55, 0x4b, 0xdf, 0xa4, 0xfa, 0x7b, 0x73, 0xa1, 0x17, 0xd9, 0xd4, 0x0f, 0xe5, 0xd5, 0xfe,
	0x5c, 0xce, 0x65, 0x51, 0x36, 0xcd, 0x66, 0xe8, 0x15, 0x0c, 0x63, 0x15, 0x0c, 0xef, 0xbb, 0x05,
	0x36, 0xe5, 0x69, 0x22, 0xe3, 0x94, 0x13, 0x07, 0x9a, 0x69, 0x16, 0x86, 0x3c, 0x4d, 0x1d, 0x6b,
	0x60, 0x0d, 0x6d, 0x7a, 0xeb, 0x92, 0x97, 0x50, 0xe7, 0x4a, 0x49, 0xe5, 0xd4, 0x06, 0xd6, 0xb0,
	0x7d, 0xd0, 0xf7, 0xd7, 0x1c, 0xed, 0x1f, 0x1b, 0x05, 0x2d, 0x84, 0xe4, 0x01, 0xd4, 0xb5, 0xbc,
	0xe4, 0xb1, 0x53, 0x1f, 0x58, 0xc3, 0x16, 0x2d, 0x1c, 0x13, 0x5d, 0x06, 0x91, 0x60, 0x4e, 0x13,
	0xf9, 0x85, 0x43, 0xde, 0xc0, 0x96, 0x88, 0x67, 0xd2, 0xb1, 0x11, 0xbe, 0xbb, 0x16, 0x3e, 0xca,
	0xf4, 0xe2, 0x34, 0x9e, 0xc9, 0x71, 0x67, 0x95, 0xbb, 0x2d, 0x13, 0x9a, 0x98, 0x1a, 0x8a, 0x95,
	0xde, 0x17, 0x68, 0x52, 0xfe, 0x39, 0xe3, 0xa9, 0xae, 0x60, 0xd6, 0xdf, 0xc2, 0x4c, 0x93, 0x91,
	0x9c, 0x8b, 0x18, 0x87, 0xb5, 0x69, 0xe1, 0xac, 0x1f, 0xc8, 0x3b, 0x84, 0x3a, 0x8e, 0x4d, 0x08,
	0x6c, 0x85, 0x92, 0x71, 0x3c, 0xb6, 0x4e, 0xd1, 0x26, 0x0f, 0xa1, 0xc1, 0xb8, 0x0e, 0x44, 0x84,
	0xa4, 0x16, 0x2d, 0x3d, 0xef, 0x5b, 0x0d, 0xec, 0xdb, 0x16, 0x48, 0x17, 0x36, 0x05, 0xc3, 0xb2,
	0x0e, 0xdd, 0x14, 0x8c, 0xf4, 0xa0, 0x96, 0x09, 0x86, 0x15, 0x1d, 0x6a, 0x4c, 0xd2, 0x07, 0x7b,
	0xc9, 0x95, 0x98, 0x09, 0xce, 0xf0, 0x70, 0x9b, 0x56, 0x3e, 0xf9, 0x04, 0xb6, 0x69, 0xff, 0xe2,
	0x3a, 0xe1, 0xb8, 0xd3, 0xee, 0x1f, 0x26, 0x36, 0xa2, 0xb1, 0x5b, 0x4d, 0xac, 0xaf, 0x13, 0x7e,
	0x93, 0xbb, 0x5d, 0x36, 0x7d, 0xed, 0x55, 0x01, 0x8f, 0x56, 0x3c, 0x72, 0x08, 0x0d, 0x63, 0x9f,
	0x32, 0xa7, 0x65, 0xda, 0x1f, 0x3f, 0x5e, 0xe5, 0x6e, 0xb3, 0x58, 0x16, 0xbb, 0xc9, 0xdd, 0xff,
	0xaa, 0x42, 0xc1, 0x3c, 0x5a, 0x4a, 0xc9, 0x53, 0x80, 0x50, 0x71, 0xc6, 0x63, 0x2d, 0x82, 0xc8,
	0x69, 0xe3, 0xdc, 0x3f, 0x45, 0xc8, 0x2b, 0xe8, 0x44, 0x81, 0xe6, 0xa9, 0x3e, 0x33, 0x5b, 0x1d,
	0x69, 0xa7, 0x33, 0xb0, 0x86, 0xb5, 0xf1, 0xce, 0x2a, 0x77, 0xb7, 0x8b, 0xc4, 0x04, 0xf7, 0x3d,
	0x09, 0x34, 0xfd, 0x55, 0x49, 0x9e, 0x41, 0x43, 0x24, 0x23, 0xc6, 0x94, 0xb3, 0x8d, 0xfd, 0xb4,
	0x4d, 0x3f, 0x22, 0x99, 0x04, 0x8c, 0x29, 0x5a, 0xa6, 0xc8, 0x0b, 0x68, 0x85, 0x8a, 0x07, 0x9a,
	0xb3, 0x91, 0x76, 0xfe, 0x47, 0x76, 0x77, 0x95, 0xbb, 0x50, 0x06, 0x0d, 0xf6, 0x4e, 0x60, 0xd4,
	0x59, 0xc2, 0x4a, 0xf5, 0xce, 0x9d, 0xba, 0x0c, 0xa2, 0xba, 0x12, 0x3c, 0xdf, 0x2b, 0x3e, 0x1b,
	0x2e, 0xa7, 0x05, 0xf5, 0xe3, 0xab, 0x40, 0x44, 0xbd, 0x0d, 0x02, 0xd0, 0x78, 0x27, 0xa7, 0x22,
	0xe2, 0x3d, 0xcb, 0xd8, 0x27, 0xf8, 0x00, 0x7b, 0x9b, 0x07, 0x5f, 0x6b, 0xb0, 0x65, 0xf4, 0xe4,
	0x03, 0x6c, 0x1f, 0x2d, 0x78, 0x78, 0x79, 0x74, 0xb7, 0x86, 0x27, 0x6b, 0xbf, 0x52, 0x79, 0x87,
	0xfb, 0xbb, 0xbf, 0xc9, 0x16, 0xef, 0xd4, 0xdb, 0x20, 0xe7, 0x40, 0x46, 0x8c, 0xe1, 0x62, 0xfe,
	0x1d, 0xf4, 0x0c, 0xda, 0x1f, 0xcd, 0xbd, 0xba, 0xbe, 0xc0, 0xb7, 0x7a, 0x4f, 0xda, 0x5b, 0x68,
	0x9e, 0x8b, 0x79, 0xfc, 0x7e, 0x36, 0xbb, 0x2f, 0xe9, 0x04, 0x1a, 0x48, 0xba, 0x6f, 0x4b, 0xd3,
	0x06, 0xfe, 0xf3, 0x0e, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0x11, 0x35, 0x9b, 0x56, 0x54, 0x05,
	0x00, 0x00,
}
